#echo -e "\e[36m>>>>>>>>> Create ${component} Service <<<<<<<<<<<<\e[0m" | tee -a /tmp/roboshop.log
#cp ${component}.service /etc/systemd/system/${component}.service &>>${log}
#func_exit_status

#echo -e "\e[36m>>>>>>>>> Start ${component} Service <<<<<<<<<<<<\e[0m" | tee -a /tmp/roboshop.log
#systemctl daemon-reload &>>${log}
#systemctl enable ${component} &>>${log}
#systemctl restart ${component} &>>${log}
#func_exit_status

- name: Setup systmd service file
  ansible.builtin.systemd:
    src: {{component}}.service
    dest: /etc/systemn.systemd:
    name: d/system/${{component}}.service

- name: Start ${{component}} Service
  ansible.builtin.systemd:
   name: {{component}}
   state: restarted
   enabled: yes
   daemon: yes
